# Generated by Django 4.2.7 on 2023-11-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(),
        ),
    ]
