# Generated by Django 4.2.7 on 2023-11-02 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_projects_end_date_alter_projects_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.AddField(
            model_name='projects',
            name='priority',
            field=models.CharField(choices=[('', 'Select Priority'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('', 'Select Priority'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('projectusers_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_project_owner', models.BooleanField(default=False)),
                ('user_role', models.CharField(max_length=50)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ManyToManyField(through='base.ProjectUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
